Migrated to null safety version
ALMaclaine/dart_string_stats pull request #1
Opened 2021-04-14 06:37 UTC by trustmefelix

2021-04-15 03:26 UTC, ALMaclaine requested changes
Hey, thanks for the contribution.

Looks fine overall and plan to merge.

Before so, can you please address the following items:

1. Fix the comment in the code review
2. Give a short justification for the changes

2021-04-15 03:26 UTC, ALMaclaine commented on pubspec.yaml
> +  pedantic: ^1.9.2
Will you add a new line here please?

2021-04-15 03:51 UTC, trustmefelix commented on pubspec.yaml
> +  pedantic: ^1.9.2
Thanks for reminding, these packages were used on my own logic checking, and now have been removed.

2021-04-15 03:57 UTC, merged

2021-04-15 21:23 UTC, ALMaclaine commented
@trustmefelix Hey I ran the tests today before publishing and one test is failing now:

00:01 +22 -1: test/string_stats_test.dart: processing_function_tests StatisticsCounter works [E]
  type '_CompactLinkedHashSet<Position?>' is not a subtype of type 'Set<Position>' of 'other'
  dart:collection                                                            SetMixin.union
  package:string_stats/src/string_statistics.dart 34:75                      StringStatistics.combine.<fn>.<fn>
  dart:collection                                                            MapMixin.update
  package:string_stats/src/string_statistics.dart 34:49                      StringStatistics.combine.<fn>
  dart:collection                                                            _LinkedHashMapMixin.forEach
  package:string_stats/src/string_statistics.dart 34:10                      StringStatistics.combine
  package:string_stats/src/processing_classes/statistics_counter.dart 31:22  StatisticsCounter.add
  test/tests/processing_class.tests.dart 58:26                               processing_class_tests.<fn>.<fn>

00:01 +25 -1: Some tests failed.

2021-04-16 02:12 UTC, trustmefelix commented
> @trustmefelix Hey I ran the tests today before publishing and one test is failing now:
> 
> 00:01 +22 -1: test/string_stats_test.dart: processing_function_tests StatisticsCounter works [E]
> type '_CompactLinkedHashSet<Position?>' is not a subtype of type 'Set' of 'other'
> dart:collection SetMixin.union
> package:string_stats/src/string_statistics.dart 34:75 StringStatistics.combine..
> dart:collection MapMixin.update
> package:string_stats/src/string_statistics.dart 34:49 StringStatistics.combine.
> dart:collection _LinkedHashMapMixin.forEach
> package:string_stats/src/string_statistics.dart 34:10 StringStatistics.combine
> package:string_stats/src/processing_classes/statistics_counter.dart 31:22 StatisticsCounter.add
> test/tests/processing_class.tests.dart 58:26 processing_class_tests..
> 
> 00:01 +25 -1: Some tests failed.

@ALMaclaine The code has been updated and run the unit test, and all test passed. Please kindly help to review it.

2021-04-16 02:43 UTC, ALMaclaine commented
I'm sorry, I don't understand what you mean.

2021-04-16 02:57 UTC, trustmefelix commented
@ALMaclaine I just updated my branch for this bug fix.